KIBON 1er DAN:
  Enchaînements membres supérieurs:
    color: 'ff6600'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    color: 'ff9955'
    image: SI.svg
  Enchaînements membres inférieurs:
    color: 'ffccaa'
    image: I.svg
KIBON 2ème DAN:
  Enchaînements membres supérieurs:
    color: '447821'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    color: '71c837'
    image: SI.svg
  Enchaînements membres inférieurs:
    color: 'aade87'
    image: I.svg
KIBON 3ème DAN:
  Enchaînements membres supérieurs:
    color: '214478'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    color: '3771c8'
    image: SI.svg
  Enchaînements membres inférieurs:
    color: '87aade'
    image: I.svg
KIBON 4ème DAN:
  Enchaînements membres supérieurs:
    color: 'd40055'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    color: 'ff2a7f'
    image: SI.svg
  Enchaînements membres inférieurs:
    color: 'ff80b2'
    image: I.svg
KIBON 5ème DAN:
  Enchaînements membres supérieurs:
    color: '241c22'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    color: '6c5367'
    image: SI.svg
  Enchaînements membres inférieurs:
    color: 'ac93a7'
    image: I.svg
