KIBON 1er DAN:
  Enchaînements membres supérieurs:
    couleur: 'd45500'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    couleur: 'ff7f2a'
    image: SI.svg
  Enchaînements membres inférieurs:
    couleur: 'ffccaa'
    image: I.svg
KIBON 2ème DAN:
  Enchaînements membres supérieurs:
    couleur: '2d5016'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    couleur: '5aa02c'
    image: SI.svg
  Enchaînements membres inférieurs:
    couleur: 'aade87'
    image: I.svg
KIBON 3ème DAN:
  Enchaînements membres supérieurs:
    couleur: '162d50'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    couleur: '2c5aa0'
    image: SI.svg
  Enchaînements membres inférieurs:
    couleur: '87aade'
    image: I.svg
KIBON 4ème DAN:
  Enchaînements membres supérieurs:
    couleur: 'aa0044'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    couleur: 'ff0066'
    image: SI.svg
  Enchaînements membres inférieurs:
    couleur: 'ff80b2'
    image: I.svg
KIBON 5ème DAN:
  Enchaînements membres supérieurs:
    couleur: '241c22'
    image: S.svg
  Enchaînements membres supérieurs et membres inférieurs:
    couleur: '483745'
    image: SI.svg
  Enchaînements membres inférieurs:
    couleur: 'ac93a7'
    image: I.svg
